### ISSUE TITLE
Huge memory usage

### ISSUE THREAD

**Issue by hudja** [popgenmethods/smcpp#38]
Hi, I have a memory usage problem. My dataset includes around 60 complete human genomes (chromosomes 1 to 22). My run failed, when I requested 300Gb of memory on hpc cluster.

-bash-4.2$ more 4205026.out
Sun Jul 23 02:59:09 EEST 2017
2458 smcpp.analysis INFO Loading data...
36979 smcpp.analysis INFO 2.99 Gb of data
37003 smcpp.analysis INFO 1 population
slurmstepd: Job 4205026 exceeded memory limit (552496700 > 314572800), being kil
led
slurmstepd: Exceeded job memory limit
slurmstepd: *** JOB 4205026 CANCELLED AT 2017-07-23T03:00:08 ***

My system is 
-bash-4.2$ uname -a
Linux ebc201 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

-bash-4.2$ cat /etc/*-release
CentOS Linux release 7.2.1511 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.2.1511 (Core) 
CentOS Linux release 7.2.1511 (Core) 

Is there any workaround to fix it?
Thank you in advance!
Best regards,
Georgi

**Comment by youngchan919** [comment]
In my condition, when operated on datasets of 1k human, the estimating process requires 16 EB for RAM usage. Here is the error info:

```
9872 smcpp.analysis INFO theta: 0.000100
9872 smcpp.analysis INFO rho: 0.000100
9872 smcpp.analysis INFO Thinning...
GNU MP: Cannot allocate memory (size=18446744073709551432)
stack trace:
  /lib64/libc.so.6 : ()+0x35250
  /lib64/libc.so.6 : gsignal()+0x37
  /lib64/libc.so.6 : abort()+0x148
  /hwfssz1/BIGDATA_COMPUTING/software/lib64/libgmp.so.3 : ()+0xc7d5
  /hwfssz1/BIGDATA_COMPUTING/software/lib64/libgmp.so.3 : __gmp_tmp_reentrant_alloc()+0x19
  /hwfssz1/BIGDATA_COMPUTING/software/lib64/libgmp.so.3 : ()+0x24cd8
  /hwfssz1/BIGDATA_COMPUTING/software/lib/python3.5/site-packages/smcpp/_smcpp.cpython-35m-x86_64-linux-gnu.so : calculate_Wnbj(int, int, int)+0x353
  /hwfssz1/BIGDATA_COMPUTING/software/lib/python3.5/site-packages/smcpp/_smcpp.cpython-35m-x86_64-linux-gnu.so : cached_matrices(int)+0x970
  /hwfssz1/BIGDATA_COMPUTING/software/lib/python3.5/site-packages/smcpp/_smcpp.cpython-35m-x86_64-linux-gnu.so : OnePopConditionedSFS<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1> > >::OnePopConditionedSFS(int)+0x47
  /hwfssz1/BIGDATA_COMPUTING/software/lib/python3.5/site-packages/smcpp/_smcpp.cpython-35m-x86_64-linux-gnu.so : OnePopInferenceManager::OnePopInferenceManager(int, std::vector<int, std::allocator<int> >, std::vector<int*, std::allocator<int*> >, std::vector<double, std::allocator<double> >, double)+0x3e
  /hwfssz1/BIGDATA_COMPUTING/software/lib/python3.5/site-packages/smcpp/_smcpp.cpython-35m-x86_64-linux-gnu.so : ()+0x5edfa
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5() [0x494083]
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyObject_Call()+0x60
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyEval_EvalFrameEx()+0x3baa
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyEval_EvalFrameEx()+0x91fb
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyEval_EvalFrameEx()+0x91fb
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5() [0x4fdca1]
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyEval_EvalCodeEx()+0x48
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5() [0x5a2cdc]
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyObject_Call()+0x60
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5() [0x595ffd]
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyObject_Call()+0x60
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5() [0x4976eb]
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5() [0x49410a]
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyObject_Call()+0x60
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyEval_EvalFrameEx()+0x3baa
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyEval_EvalFrameEx()+0x91fb
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyEval_EvalFrameEx()+0x91fb
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5() [0x4fdca1]
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyEval_EvalCode()+0x4d
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyRun_FileExFlags()+0x168
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : PyRun_SimpleFileExFlags()+0xdd
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : Py_Main()+0xcbb
  /hwfssz1/BIGDATA_COMPUTING/software/bin/python3.5 : main()+0x152
  /lib64/libc.so.6 : __libc_start_main()+0xf5
```

I am wondering if algorithm optimization is the only method to solve the problem?

**Comment by terhorst** [comment]
What sample size are you attempting to analyze?

**Comment by terhorst** [comment]
@hudja I think I have fixed your problem, I will release an update today or tomorrow with the patch.

**Comment by youngchan919** [comment]
The vcf.gz file occupies ~ 2.8G, I think the vcf file will be ~ 100G.
I am looking forward to your new release. Thank you so much.

**Comment by terhorst** [comment]
@youngchan919 how many diploid samples are you using in your analysis?

**Comment by youngchan919** [comment]
1000 low-depth samples. And if the problem is solved, we are going to use smc++ for datasets with over 10k samples as well.

**Comment by youngchan919** [comment]
Well, I used the smcpp-1.9.3-Linux-x86_64.sh to install another smc++, which I thought was compiled based on my environment. But the same error still issued. Could you please tell me how to fix this problem? Thank you.

**Comment by terhorst** [comment]
@youngchan919 It is compiled based on a generic Linux environment. This seems to work for most people, but apparently it fails on your system. You might try compiling it yourself as @hudja did. Also, the largest sample size I have ever analyzed using SMC++ is n=300. I think n=1000 is probably feasible but n=10k would probably require a huge amount of memory and computation time.

**Comment by youngchan919** [comment]
# @terhorst When I tried it for n=100, everything worked well. I guess the n limit possibly exists for all users...

**Comment by youngchan919** [comment]
@terhorst When I tried it for n=100, everything worked well. I guess the n limit possibly exists for all users...

**Comment by oushujun** [comment]
Hi @terhorst,

I think @youngchan919's last comment is right. I run on rice populations (genome size ~= 380 M), when population size exceeds a certain number, smc++ quit for not enough memory (usually an unrealistic number). In my case, smc++ can run 388 individuals without a problem, but for the case of `446`, `630`, `1012`, and `1827` individuals, the program exit by asking memory of `18446744073709551448`, `18446744073709551464`, `18446744073709551424`, and `18446744073709551400`, respectively. These numbers differ only on the last two digits, as well as for @youngchan919 's case. So I am not sure whether there is some sort of bugs in the program or just a coincidence. 

Thanks,
Shujun

**Comment by oushujun** [comment]
@terhorst I looked at the discussions in #73, imputation does not solve my problem, because my data are imputed and contains no missing data (although long-run of homozygosity was reported probably due to the selfing nature of the organism).

**Comment by terhorst** [comment]
@oushujun The biggest sample size I have analyzed used SMC++ is around 400. Unfortunately, I do not think that the amount of memory it requests for larger sample sizes is the result of an error. In order for the program to run a certain `n x n` matrix must be precomputed. The matrix is computed recursively, so computing it takes`O(n^3)` space at least. Worse, the recursion is numerically unstable (alternating signs) so accurately compute this matrix we have to use extended precision arithmetic. The amount (bits) of precision needed scales with the dimension of the matrix. Long story short, it's fairly memory intensive and I don't know of an easy way to lower the memory requirement.

**Comment by oushujun** [comment]
@terhorst  Is it possible (or easy) to introduce another thinning mechanism but for the sample size? For different organism/data, it seems to be a turning point of sample size that smc++ request +++++ memory.

**Comment by terhorst** [comment]
@oushujun You can downsample the data by dropping columns from the VCF, sure. Other than that, I currently do not have any other way around the problems I mentioned above within the SMC++ framework. I am working on a completely different method for handling huge sample sizes that does not suffer from these problems, but it is not yet ready for release.
